export const keywords = [
  "Zaheer Ali Shaikh",
  "Zaheer",
  "Shaikh",
  "xaheer-shaikh", // GitHub username
  "aarab.vercel.app", // Portfolio URL
  "zaheerocean@gmail.com", // Email for search
  "linkedin/in/xaheer-shaikh", // LinkedIn profile
  "Zaheer Ali Shaikh portfolio",
  "Zaheer Ali Shaikh developer",
  "Zaheer Ali Shaikh software engineer",
  "Zaheer Ali Shaikh web developer",
  "Zaheer Ali Shaikh AI developer",
  "Zaheer Ali Shaikh full-stack developer",
  "Zaheer Ali Shaikh projects",
  "Zaheer Ali Shaikh resume",
  "Zaheer Ali Shaikh contact",

  "student developer portfolio",
  "web developer Bhubaneswar",
  "frontend developer India",
  "full-stack engineer portfolio",
  "open source web developer",
  "Next.js frontend portfolio",
  "React developer personal site",
  "software engineer portfolio",
  "AI developer portfolio",
  "Machine Learning Engineer",
  "Content Development Tech",
  "Unstop developer",
  "coding question developer",
  "technical question curator",
  "data bug resolution",
  "cloud developer",
  "DevOps enthusiast",
  "entry-level software engineer",
  "junior web developer",

  "C programming",
  "C++ programming",
  "Java developer",
  "JavaScript developer",
  "TypeScript developer",
  "Python developer",
  "HTML/CSS development",

  "React.js developer",
  "Next.js developer",
  "Framer Motion animations",
  "Tailwind CSS design",
  "Bootstrap framework",
  "ShadCN UI components",
  "responsive web design",
  "UI/UX development",
  "modern UI development",
  "Next.js Server Components",
  "Next.js Client Components",
  "CSS Modules",
  "SCSS",
  "Redux state management",

  "Express.js backend",
  "API Design",
  "MongoDB database",
  "Oracle SQL",
  "MySQL database",
  "PostgreSQL database",
  "Prisma ORM",
  "drizzle ORM",
  "serverless functions",
  "Next.js API routes",
  "Convex backend database",
  "REST API development",
  "GraphQL API",
  "WebSockets",

  "BERT model",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Large Language Models (LLMs)",
  "LLaMA language model",
  "LangChain developer",
  "Gemini API integration",
  "Hugging Face API for AI",
  "Ollama local LLM",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Prompt Engineering",
  "AI model fine-tuning",
  "TensorFlow",
  "PyTorch",
  "Keras",

  "Git version control",
  "GitHub collaboration",
  "Postman API testing",
  "Jest testing setup",
  "unit testing in Next.js",
  "API integration with Next.js",
  "Clerk authentication Next.js",
  "Firebase hosting",
  "Netlify deployment",
  "Vercel deployment",
  "Glitch development",
  "Replit development",
  "Docker developer",
  "Kubernetes basics",
  "CI/CD with GitHub Actions",
  "VS Code extensions",
  "Webpack",
  "Vite",
  "Figma UI/UX design",

  "Orphia AI Music Generator",
  "AI-powered music generation platform",
  "Meta MusicGen integration",
  "Custom LSTM model music",
  "Next.js music UI",
  "music personalization AI",
  "audio synthesis AI",
  "CppTest GenAI",
  "AI-powered C++ test generator",
  "LLaMA language model C++",
  "intelligent unit test scenarios",
  "automated test case generation",
  "test accuracy improvement",
  "CI/CD pipeline integration",
  "personal portfolio website Next.js",
  "EmailJs integration",
  "Framer Motion portfolio",
  "SEO optimization portfolio",
  "structured metadata website",
  "Open Graph tags SEO",
  "Google PageSpeed Insights optimization",
  "performance optimization web",
  "accessibility best practices",
  "AI mood journal app",
  "Instagram reel downloader app",
  "reel download tool",
  "Next.js story app",
  "24Verse stories app",
  "text to music AI generator",
  "resume parser AI",
  "developer resume scanner",
  "bug tracker app Next.js",
  "build your own API project",
  "real-time chat application",
  "e-commerce platform development",
  "portfolio website builder",
  "custom AI chatbot",
  "image generation AI project",
  "sentiment analysis tool",
  "full-stack project examples",
  "web application development",

  "HackerRank Problem Solving Certificate",
  "Scientific Computing with Python FreeCodeCamp",
  "Software Development Trainee AMCAT",
  "Data Processing Specialist AMCAT",
  "Business Analyst Certificate AMCAT",

  "best student portfolios 2025",
  "react portfolio example 2025",
  "Next.js app directory project",
  "modern web development portfolio",
  "best open source portfolio projects",
  "developer website examples",
  "personal web developer site",
  "tech blog and portfolio",
  "build portfolio with Tailwind CSS",
  "interactive resume website",
  "coding portfolio examples",
  "developer with AI projects",
  "best portfolio with AI features",
  "free tools for developers",
  "developer website inspiration",
  "SEO optimized portfolio site",
  "how to build a developer portfolio",
  "showcase coding projects",
  "web development trends 2025",
  "computer science student projects",
  "B.Tech Computer Science portfolio",
  "KIIT student developer",
  "hire Next.js developer",
  "hire React developer",
  "freelance web developer",
  "internship software development",
  "student developer looking for job",

  "JavaScript",
  "TypeScript",
  "HTML",
  "CSS",
  "Next.js",
  "React",
  "Tailwind",
  "Framer Motion",
  "PostgreSQL",
  "MongoDB",
  "Oracle SQL",
  "MySQL",
  "Jest",
  "Vercel",
  "Clerk",
  "Convex",
  "LLM",
  "Ollama",
  "GitHub Actions",
  "API routes",
  "app router",
  "responsive UI",
  "dark mode toggle",
  "UI/UX",
  "full-stack",
  "AI",
  "Machine Learning",
  "Deep Learning",
  "BERT",
  "LSTM",
  "LLaMA",
  "Cloud Computing",
  "Firebase",
  "GraphQL",
  "REST API",
  "WebSockets",
  "Git",
  "GitHub",
  "VS Code",
  "Node.js",
  "Express.js",
  "Python",
  "C",
  "C++",
  "Java",
  "Data Structures and Algorithms",
  "DSA",
  "Object-Oriented Programming",
  "OOP",
  "Functional Programming",
  "System Design",
  "Agile development",
  "Clean Code",
  "Scalable architecture",
];
