export const resumeKeywords = [
  // Personal Branding
  "Zaheer Ali Shaikh",
  "Zaheer Ali Shaikh resume",
  "Zaheer Ali Shaikh CV",
  "Software Developer",
  "Full Stack Developer",
  "Mobile App Developer",
  "Frontend Developer",
  "Backend Developer",
  "Web Developer",
  "Flutter Developer",
  "AI Developer",
  "Student Developer",
  "Software Engineer",
  "University of Mumbai",

  // Core Programming Languages
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C",
  "Dart",
  "Kotlin",
  "Rust",
  "Go",
  "HTML5",
  "CSS3",
  "SQL",
  "NoSQL",

  // Frontend Technologies
  "React.js",
  "Next.js",
  "React Native",
  "Vue.js",
  "Angular",
  "Tailwind CSS",
  "Bootstrap",
  "ShadCN UI",
  "Material UI",
  "Framer Motion",
  "SCSS",
  "CSS Modules",
  "Responsive Design",
  "Mobile First Design",
  "Cross Browser Compatibility",
  "Progressive Web Apps",
  "Single Page Applications",
  "SPA",

  // Backend Technologies
  "Node.js",
  "Express.js",
  "Next.js API Routes",
  "RESTful APIs",
  "GraphQL",
  "WebSockets",
  "Microservices",
  "Serverless Functions",
  "API Design",
  "API Integration",
  "Authentication",
  "Authorization",
  "JWT",
  "OAuth",

  // Databases
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase Firestore",
  "Prisma ORM",
  "Drizzle ORM",
  "Database Design",
  "Data Modeling",
  "Database Optimization",
  "ACID Properties",
  "Database Indexing",

  // Cloud & DevOps
  "AWS",
  "Google Cloud Platform",
  "Microsoft Azure",
  "Vercel",
  "Netlify",
  "Firebase",
  "Docker",
  "Kubernetes",
  "CI/CD",
  "GitHub Actions",
  "Jenkins",
  "Git",
  "GitHub",
  "GitLab",
  "Version Control",
  "Deployment",
  "Serverless Architecture",

  // AI / ML Technologies
  "Machine Learning",
  "Deep Learning",
  "Neural Networks",
  "Natural Language Processing",
  "NLP",
  "Computer Vision",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "scikit-learn",
  "Large Language Models",
  "LLM",
  "Generative AI",
  "OpenAI API",
  "ChatGPT API",
  "Hugging Face",
  "LangChain",
  "Prompt Engineering",
  "AI Model Training",
  "Data Analysis",
  "Data Science",

  // Testing & QA
  "Unit Testing",
  "Integration Testing",
  "End-to-End Testing",
  "Test Driven Development",
  "TDD",
  "Jest",
  "Cypress",
  "Playwright",
  "React Testing Library",
  "Postman",
  "API Testing",
  "Bug Tracking",
  "Quality Assurance",
  "Code Review",
  "Debugging",

  // Software Development Practices
  "Agile Development",
  "Scrum",
  "Kanban",
  "Object Oriented Programming",
  "OOP",
  "Functional Programming",
  "Clean Code",
  "SOLID Principles",
  "Design Patterns",
  "MVC Architecture",
  "System Design",
  "Scalable Architecture",
  "Performance Optimization",
  "Refactoring",
  "Technical Documentation",

  // Data Structures & Algorithms
  "Data Structures",
  "Algorithms",
  "Big O Notation",
  "Arrays",
  "Linked Lists",
  "Stacks",
  "Queues",
  "Trees",
  "Graphs",
  "Hash Tables",
  "Sorting Algorithms",
  "Searching Algorithms",
  "Dynamic Programming",
  "Recursion",
  "Problem Solving",

  // Tools & IDEs
  "Visual Studio Code",
  "VS Code",
  "IntelliJ IDEA",
  "Eclipse",
  "Sublime Text",
  "Vim",
  "Webpack",
  "Vite",
  "Babel",
  "ESLint",
  "Prettier",
  "npm",
  "yarn",
  "pnpm",

  // Soft Skills
  "Problem Solving",
  "Critical Thinking",
  "Team Collaboration",
  "Communication Skills",
  "Leadership",
  "Project Management",
  "Time Management",
  "Adaptability",
  "Self-Motivated",
  "Detail Oriented",
  "Analytical Thinking",
  "Creative Problem Solving",
  "Continuous Learning",
  "Mentoring",
  "Code Review",

  // Industry Experience
  "Internship",
  "Entry Level",
  "Junior Developer",
  "Software Development Trainee",
  "Open Source Contributor",
  "Freelance Developer",
  "Project Based Work",
  "Team Projects",
  "Solo Projects",
  "Academic Projects",
  "Personal Projects",
  "Portfolio Projects",

  // Project Categories
  "Web Applications",
  "Mobile Applications",
  "Desktop Applications",
  "E-commerce Platform",
  "Portfolio Website",
  "Blog Platform",
  "Social Media App",
  "Chat Application",
  "Task Management System",
  "Content Management System",
  "CMS",
  "API Development",
  "Microservices",
  "Real-time Applications",
  "Data Visualization",
  "AI Projects",
  "Machine Learning Projects",

  // Location & Availability
  "Thane",
  "Mumbai",
  "India",
  "Remote Work",
  "Hybrid Work",
  "Full Time",
  "Part Time",
  "Contract",
  "Internship",
  "Available Immediately",
  "Flexible Schedule",

  // Education Keywords
  "Computer Engineering",
  "Electronics & Computer Science",
  "B.E. Engineering",
  "University of Mumbai",
  "Diploma in Computer Engineering",
  "MSBTE Mumbai",
  "CEH Trainee",
  "Academic Projects",
  "Capstone Project",
  "Technical Skills",
  "Coursework",
  "Data Structures & Algorithms",
  "DBMS",
  "Software Development",
  "Computer Networks",
  "Programming",
  "Database Management",
  "Networking",

  // Industry Buzzwords
  "Digital Transformation",
  "Innovation",
  "Technology Solutions",
  "Software Solutions",
  "User Experience",
  "UX",
  "User Interface",
  "UI",
  "Cross-functional Teams",
  "Stakeholder Management",
  "Requirements Analysis",
  "Technical Specifications",
  "Code Documentation",
  "Best Practices",
];
